require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
$min_deployment_target = 9.0

target 'example' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  target 'exampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!({ 'Flipper' => '0.140.0' })

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    fix_deployment_target(installer)
  end

end

def fix_deployment_target(installer)
  return if !installer
  new_target = $min_deployment_target.to_s

  puts "Make sure all pods deployment target is minimum set at #{new_target.green}"
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < $min_deployment_target
        old_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        if config.name == "Release"
          puts "  #{target.name.blue}: #{old_target.yellow} -> #{new_target.green}"
        end
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = new_target
      end
    end
  end
end
